name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build it
        working-directory: ./my-app
        env:
          secrets_PAT: ${{ secrets.PAT }}
        run: |
          git config --global credential.https://github.com.username git
          git config --global credential.https://github.com.password $secrets_PAT
          npm i
          npm ci
          npm run build
          npm run deploy # this just pushes it to gh-pages branch, Settings > Pages handles it from there... 