name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        working-directory: ./my-app
        run: npm ci

      - name: Build
        working-directory: ./my-app
        run: npm run build

      - name: Deploy
        working-directory: ./my-app
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          BRANCH: gh-pages # The branch the action should deploy to.